Instalación y Configuration de Linters #19
DevsDO/whocode-frontend pull request #25
Opened 2020-09-11 01:36 UTC by nathzz30

Este PR es para subir las configuraciones basicas de los linters. Se creo el .**editorconfig**, se instalo **ESlint**, **Prettier**, y **husky**. Se configuraron de forma básica los hooks para el `pre-commit`, `pre-push` y `post-push`.

2020-09-11 01:40 UTC, sperezm97 commented
Hola ! @nathzz30, Estamos usando [yarn](https://yarnpkg.com/). Para el manejo de los paquetes, por favor actualizar el Pull request con esos cambios. 

- [ ] Debes eliminar el `package-lock.json` y instalar con yarn.

2020-09-11 01:45 UTC, sperezm97 requested changes

2020-09-11 01:45 UTC, sperezm97 commented on package.json
> +      "eslint src/*.js --fix-dry-run"
La configuration del eslint esta erronea, solo estaremos utilizando typescript en el proyecto.
```suggestion
      "eslint . --fix-dry-run"
```

2020-09-11 01:45 UTC, sperezm97 commented on package.json
> +    "./src/*.{js,jsx,ts,tsx}": [
Modificar esta parte par que solo se admita archivos {ts, .tsx}
```suggestion
    "./src/*.{ts,tsx}": [
```

2020-09-11 01:45 UTC, sperezm97 commented on .editorconfig
> +indent_size = 2
No estamos usando sass ni scss. Deberias eliminarlo.

2020-09-11 01:57 UTC, dionicio-gp commented on package.json
> +    "eslint": "^7.2.0",
hi @nathzz30  creo que nos podriamos beneficiar de este [enlace](https://www.gatsbyjs.com/plugins/gatsby-plugin-prettier-eslint/).

2020-09-11 02:04 UTC, mecm1993 commented
ya que @nathzz30 esta modificando el `package.json` seria bueno aprovecharla para que modifique lo siguiente,

```json
  "name": "whocode-frontend",
  "private": true,
  "description": "discovery site for all Dominican developers with their skills and contacts",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>", // esta parte se puede remover
  ...
  "repository": {
    "type": "git",
    "url": "https://github.com/DevsDO/whocode-frontend"
  },
  "bugs": {
    "url": "https://github.com/DevsDO/whocode-frontend/issues"
  }
```

2020-09-13 22:31 UTC, sperezm97 commented
@nathzz30 Hello, ahora dandole un check, no vi que hayas instalado la integración de [typescript para el eslint](https://medium.com/@myylow/how-to-keep-the-airbnb-eslint-config-when-moving-to-typescript-1abb26adb5c6)

2020-09-22 00:19 UTC, mecm1993 commented
@sperezm97 y @dionicio-gp cuando puedan el review para @nathzz30

2020-09-22 00:37 UTC, dionicio-gp approved these changes

2020-09-25 01:41 UTC, mecm1993 commented
hola @nathzz30 por favor resolver los conflictos, luego de esto no hay problemas para pasarlo a `development`

2020-10-01 21:46 UTC, mecm1993 approved these changes

2020-10-06 12:27 UTC, sperezm97 approved these changes

2020-10-06 12:27 UTC, merged