Ppv/issue 22
DevsDO/whocode-frontend pull request #26
Opened 2020-09-11 02:32 UTC by ppv95

Este pull request es para agregar el plugin  "Gatsby-alias-import" para facilitar la importación de componentes, styles y los pages del proyecto.

- Se Modifico el archivo Gatsby-config.js agregado los aliases.

2020-09-11 03:09 UTC, sperezm97 requested changes

2020-09-11 03:09 UTC, sperezm97 commented on package.json
> +    "gatsby-plugin-alias-imports": "^1.0.5",
Saludos @ppv95, y no se supone que `gatsby-alias-import` y `gatsby-plugin-alias-imports` hacen lo mismo, porque tenerlos ambos ?

2020-09-11 14:12 UTC, ppv95 commented on package.json
> +    "gatsby-plugin-alias-imports": "^1.0.5",
Si, lo que paso fue que cuando instale el uno me estaba marcando un error de que no encontraba el modulo (pero funciona el import con su alias ).Pero dejame verificarlo para solo tener uno.

2020-09-11 15:01 UTC, dionicio-gp commented on package.json
> +    "gatsby-plugin-alias-imports": "^1.0.5",
@ppv95 porfavor remueve de las dependencias gatsby-alias-imports. Ya que el pluggin que esta funcionando es [gatsby-plugin-alias-imports](https://www.gatsbyjs.com/plugins/gatsby-plugin-alias-imports/)

2020-09-12 18:15 UTC, ppv95 commented on package.json
> +    "gatsby-plugin-alias-imports": "^1.0.5",
@sperezm97  @dionicio-gp  Listo, favor de revisar y cualquier otra observacion favor hacermela saber. Gracias de antemano

2020-09-12 20:35 UTC, sperezm97 approved these changes

2020-09-13 00:54 UTC, dionicio-gp approved these changes
buen trabajo

2020-09-13 04:22 UTC, merged